web:
    image: tutum/apache-php
    ports:
        - "80:80"
    links:
        - db
    volumes:
        - $PWD/server:/app

db:
    image: mysql
    volumes:
        - $PWD/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: grinder_db
        MYSQL_USER: grinder_user
        MYSQL_PASSWORD: grinder_pass

